# Generated by Django 2.0.4 on 2018-04-08 19:26

import Campus.managers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('1', 'Işık Üniversitesi'), ('2', 'Abant İzzet Baysal Üniversitesi'), ('3', 'Adana Bilim ve Teknoloji Üniversitesi'), ('4', 'Adıyaman Üniversitesi'), ('5', 'Adnan Menderes Üniversitesi'), ('6', 'Afyon Kocatepe Üniversitesi'), ('7', 'Ağrı İbrahim Çeçen Üniversitesi'), ('8', 'Ahi Evran Üniversitesi'), ('9', 'Akdeniz Üniversitesi'), ('10', 'Aksaray Üniversitesi'), ('11', 'Alanya Alaaddin Keykubat Üniversitesi'), ('12', 'Amasya Üniversitesi'), ('13', 'Anadolu Üniversitesi'), ('14', 'Ankara Üniversitesi'), ('15', 'Ankara Sosyal Bilimler Üniversitesi'), ('16', 'Ardahan Üniversitesi'), ('17', 'Artvin Çoruh Üniversitesi'), ('18', 'Atatürk Üniversitesi'), ('19', 'Balıkesir Üniversitesi'), ('20', 'Bandırma Onyedi Eylül Üniversitesi'), ('21', 'Bartın Üniversitesi'), ('22', 'Batman Üniversitesi'), ('23', 'Bayburt Üniversitesi'), ('24', 'Bilecik Şeyh Edebali Üniversitesi'), ('25', 'Bingöl Üniversitesi'), ('26', 'Bitlis Eren Üniversitesi'), ('27', 'Boğaziçi Üniversitesi'), ('28', 'Bozok Üniversitesi'), ('29', 'Bursa Teknik Üniversitesi'), ('30', 'Celal Bayar Üniversitesi'), ('31', 'Cumhuriyet Üniversitesi'), ('32', 'Çanakkale Onsekiz Mart Üniversitesi'), ('33', 'Çankırı Karatekin Üniversitesi'), ('34', 'Çukurova Üniversitesi'), ('35', 'Deniz Harp Okulu'), ('36', 'Dicle Üniversitesi'), ('37', 'Dokuz Eylül Üniversitesi'), ('38', 'Dumlupınar Üniversitesi'), ('39', 'Düzce Üniversitesi'), ('40', 'Ege Üniversitesi'), ('41', 'Erciyes Üniversitesi'), ('42', 'Erzincan Üniversitesi'), ('43', 'Erzurum Teknik Üniversitesi'), ('44', 'Eskişehir Osmangazi Üniversitesi'), ('45', 'Fırat Üniversitesi'), ('46', 'Galatasaray Üniversitesi'), ('47', 'Gazi Üniversitesi'), ('48', 'Gaziantep Üniversitesi'), ('49', 'Gaziosmanpaşa Üniversitesi'), ('50', 'Gebze Teknik Üniversitesi'), ('51', 'Giresun Üniversitesi'), ('52', 'Gümüşhane Üniversitesi'), ('53', 'Hacettepe Üniversitesi'), ('54', 'Hakkari Üniversitesi'), ('55', 'Harran Üniversitesi'), ('56', 'Hava Harp Okulu'), ('57', 'Hitit Üniversitesi'), ('58', 'Iğdır Üniversitesi'), ('59', 'İnönü Üniversitesi'), ('60', 'İskenderun Teknik Üniversitesi'), ('61', 'İstanbul Medeniyet Üniversitesi'), ('62', 'İstanbul Üniversitesi'), ('63', 'İstanbul Teknik Üniversitesi'), ('64', 'İzmir Bakırçay Üniversitesi'), ('65', 'İzmir Demokrasi Üniversitesi'), ('66', 'İzmir Kâtip Çelebi Üniversitesi'), ('67', 'İzmir Yüksek Teknoloji Enstitüsü'), ('68', 'Kafkas Üniversitesi'), ('69', 'Kahramanmaraş Sütçü İmam Üniversitesi'), ('70', 'Karabük Üniversitesi'), ('71', 'Karadeniz Teknik Üniversitesi'), ('72', 'Karamanoğlu Mehmetbey Üniversitesi'), ('73', 'Kastamonu Üniversitesi'), ('74', 'Kırıkkale Üniversitesi'), ('75', 'Kilis 7 Aralık Üniversitesi'), ('76', 'Kocaeli Üniversitesi'), ('78', 'Necmettin Erbakan Üniversitesi'), ('79', 'Mardin Artuklu Üniversitesi'), ('80', 'Marmara Üniversitesi'), ('81', 'Mehmet Akif Ersoy Üniversitesi'), ('82', 'Mersin Üniversitesi'), ('83', 'Mimar Sinan Güzel Sanatlar Üniversitesi'), ('84', 'Muğla Sıtkı Koçman Üniversitesi'), ('85', 'Mustafa Kemal Üniversitesi'), ('86', 'Muş Alparslan Üniversitesi'), ('87', 'Namık Kemal Üniversitesi'), ('88', 'Nevşehir Hacı Bektaş Veli Üniversitesi'), ('89', 'Niğde Üniversitesi'), ('90', 'Ondokuz Mayıs Üniversitesi'), ('91', 'Ordu Üniversitesi'), ('92', 'Orta Doğu Teknik Üniversitesi'), ('93', 'Osmaniye Korkut Ata Üniversitesi'), ('94', 'Pamukkale Üniversitesi'), ('95', 'Sakarya Üniversitesi'), ('96', 'Selçuk Üniversitesi'), ('97', 'Siirt Üniversitesi'), ('98', 'Süleyman Demirel Üniversitesi'), ('99', 'Trakya Üniversitesi'), ('100', 'Uludağ Üniversitesi'), ('101', 'Uşak Üniversitesi'), ('102', 'Yalova Üniversitesi'), ('103', 'Yıldız Teknik Üniversitesi'), ('104', 'Yıldırım Beyazıt Üniversitesi'), ('105', 'Yüzüncü Yıl Üniversitesi'), ('106', 'Bülent Ecevit Üniversitesi'), ('107', 'Acıbadem Üniversitesi'), ('108', 'Akev Üniversitesi'), ('109', 'Anka Teknoloji Üniversitesi'), ('110', 'Atılım Üniversitesi'), ('111', 'Avrasya Üniversitesi'), ('112', 'Bahçeşehir Üniversitesi'), ('113', 'Başkent Üniversitesi'), ('114', 'Beykent Üniversitesi'), ('115', 'Bezmiâlem Vakıf Üniversitesi'), ('116', 'Bilkent Üniversitesi'), ('117', 'Biruni Üniversitesi'), ('118', 'Çankaya Üniversitesi'), ('119', 'Çağ Üniversitesi'), ('120', 'Doğuş Üniversitesi'), ('121', 'Fatih Sultan Mehmet Üniversitesi'), ('122', 'Haliç Üniversitesi'), ('123', 'İstanbul 29 Mayıs Üniversitesi'), ('124', 'İstanbul Arel Üniversitesi'), ('125', 'İstanbul Aydın Üniversitesi'), ('126', 'İstanbul Bilgi Üniversitesi'), ('127', 'İstanbul Gelişim Üniversitesi'), ('128', 'İstanbul Kemerburgaz Üniversitesi'), ('129', 'İstanbul Kültür Üniversitesi'), ('130', 'İstanbul Medipol Üniversitesi'), ('131', 'İstanbul Şehir Üniversitesi'), ('132', 'İstinye Üniversitesi'), ('132', 'İzmir Ekonomi Üniversitesi'), ('133', 'Kadir Has Üniversitesi'), ('134', 'Nişantaşı Üniversitesi'), ('135', 'Okan Üniversitesi'), ('136', 'Özyeğin Üniversitesi'), ('137', 'Piri Reis Üniversitesi'), ('138', 'Sabancı Üniversitesi'), ('139', 'TED Üniversitesi'), ('140', 'Yeditepe Üniversitesi')], default='Işık Üniversitesi', max_length=60, verbose_name='University')),
            ],
            options={
                'ordering': ['staff'],
            },
        ),
        migrations.CreateModel(
            name='CcrCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Course Number')),
                ('semester', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semester')),
            ],
            options={
                'ordering': ['ccr', 'type', 'no', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='CompletedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Completed Course',
                'verbose_name_plural': 'Completed Courses',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Course Code')),
                ('title', models.CharField(max_length=60, verbose_name='Course Title')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Course Description')),
                ('credit', models.IntegerField(verbose_name='Course Credit')),
                ('ects_credit', models.IntegerField(verbose_name='Course ECTS Credit')),
                ('university', models.CharField(choices=[('1', 'Işık Üniversitesi'), ('2', 'Abant İzzet Baysal Üniversitesi'), ('3', 'Adana Bilim ve Teknoloji Üniversitesi'), ('4', 'Adıyaman Üniversitesi'), ('5', 'Adnan Menderes Üniversitesi'), ('6', 'Afyon Kocatepe Üniversitesi'), ('7', 'Ağrı İbrahim Çeçen Üniversitesi'), ('8', 'Ahi Evran Üniversitesi'), ('9', 'Akdeniz Üniversitesi'), ('10', 'Aksaray Üniversitesi'), ('11', 'Alanya Alaaddin Keykubat Üniversitesi'), ('12', 'Amasya Üniversitesi'), ('13', 'Anadolu Üniversitesi'), ('14', 'Ankara Üniversitesi'), ('15', 'Ankara Sosyal Bilimler Üniversitesi'), ('16', 'Ardahan Üniversitesi'), ('17', 'Artvin Çoruh Üniversitesi'), ('18', 'Atatürk Üniversitesi'), ('19', 'Balıkesir Üniversitesi'), ('20', 'Bandırma Onyedi Eylül Üniversitesi'), ('21', 'Bartın Üniversitesi'), ('22', 'Batman Üniversitesi'), ('23', 'Bayburt Üniversitesi'), ('24', 'Bilecik Şeyh Edebali Üniversitesi'), ('25', 'Bingöl Üniversitesi'), ('26', 'Bitlis Eren Üniversitesi'), ('27', 'Boğaziçi Üniversitesi'), ('28', 'Bozok Üniversitesi'), ('29', 'Bursa Teknik Üniversitesi'), ('30', 'Celal Bayar Üniversitesi'), ('31', 'Cumhuriyet Üniversitesi'), ('32', 'Çanakkale Onsekiz Mart Üniversitesi'), ('33', 'Çankırı Karatekin Üniversitesi'), ('34', 'Çukurova Üniversitesi'), ('35', 'Deniz Harp Okulu'), ('36', 'Dicle Üniversitesi'), ('37', 'Dokuz Eylül Üniversitesi'), ('38', 'Dumlupınar Üniversitesi'), ('39', 'Düzce Üniversitesi'), ('40', 'Ege Üniversitesi'), ('41', 'Erciyes Üniversitesi'), ('42', 'Erzincan Üniversitesi'), ('43', 'Erzurum Teknik Üniversitesi'), ('44', 'Eskişehir Osmangazi Üniversitesi'), ('45', 'Fırat Üniversitesi'), ('46', 'Galatasaray Üniversitesi'), ('47', 'Gazi Üniversitesi'), ('48', 'Gaziantep Üniversitesi'), ('49', 'Gaziosmanpaşa Üniversitesi'), ('50', 'Gebze Teknik Üniversitesi'), ('51', 'Giresun Üniversitesi'), ('52', 'Gümüşhane Üniversitesi'), ('53', 'Hacettepe Üniversitesi'), ('54', 'Hakkari Üniversitesi'), ('55', 'Harran Üniversitesi'), ('56', 'Hava Harp Okulu'), ('57', 'Hitit Üniversitesi'), ('58', 'Iğdır Üniversitesi'), ('59', 'İnönü Üniversitesi'), ('60', 'İskenderun Teknik Üniversitesi'), ('61', 'İstanbul Medeniyet Üniversitesi'), ('62', 'İstanbul Üniversitesi'), ('63', 'İstanbul Teknik Üniversitesi'), ('64', 'İzmir Bakırçay Üniversitesi'), ('65', 'İzmir Demokrasi Üniversitesi'), ('66', 'İzmir Kâtip Çelebi Üniversitesi'), ('67', 'İzmir Yüksek Teknoloji Enstitüsü'), ('68', 'Kafkas Üniversitesi'), ('69', 'Kahramanmaraş Sütçü İmam Üniversitesi'), ('70', 'Karabük Üniversitesi'), ('71', 'Karadeniz Teknik Üniversitesi'), ('72', 'Karamanoğlu Mehmetbey Üniversitesi'), ('73', 'Kastamonu Üniversitesi'), ('74', 'Kırıkkale Üniversitesi'), ('75', 'Kilis 7 Aralık Üniversitesi'), ('76', 'Kocaeli Üniversitesi'), ('78', 'Necmettin Erbakan Üniversitesi'), ('79', 'Mardin Artuklu Üniversitesi'), ('80', 'Marmara Üniversitesi'), ('81', 'Mehmet Akif Ersoy Üniversitesi'), ('82', 'Mersin Üniversitesi'), ('83', 'Mimar Sinan Güzel Sanatlar Üniversitesi'), ('84', 'Muğla Sıtkı Koçman Üniversitesi'), ('85', 'Mustafa Kemal Üniversitesi'), ('86', 'Muş Alparslan Üniversitesi'), ('87', 'Namık Kemal Üniversitesi'), ('88', 'Nevşehir Hacı Bektaş Veli Üniversitesi'), ('89', 'Niğde Üniversitesi'), ('90', 'Ondokuz Mayıs Üniversitesi'), ('91', 'Ordu Üniversitesi'), ('92', 'Orta Doğu Teknik Üniversitesi'), ('93', 'Osmaniye Korkut Ata Üniversitesi'), ('94', 'Pamukkale Üniversitesi'), ('95', 'Sakarya Üniversitesi'), ('96', 'Selçuk Üniversitesi'), ('97', 'Siirt Üniversitesi'), ('98', 'Süleyman Demirel Üniversitesi'), ('99', 'Trakya Üniversitesi'), ('100', 'Uludağ Üniversitesi'), ('101', 'Uşak Üniversitesi'), ('102', 'Yalova Üniversitesi'), ('103', 'Yıldız Teknik Üniversitesi'), ('104', 'Yıldırım Beyazıt Üniversitesi'), ('105', 'Yüzüncü Yıl Üniversitesi'), ('106', 'Bülent Ecevit Üniversitesi'), ('107', 'Acıbadem Üniversitesi'), ('108', 'Akev Üniversitesi'), ('109', 'Anka Teknoloji Üniversitesi'), ('110', 'Atılım Üniversitesi'), ('111', 'Avrasya Üniversitesi'), ('112', 'Bahçeşehir Üniversitesi'), ('113', 'Başkent Üniversitesi'), ('114', 'Beykent Üniversitesi'), ('115', 'Bezmiâlem Vakıf Üniversitesi'), ('116', 'Bilkent Üniversitesi'), ('117', 'Biruni Üniversitesi'), ('118', 'Çankaya Üniversitesi'), ('119', 'Çağ Üniversitesi'), ('120', 'Doğuş Üniversitesi'), ('121', 'Fatih Sultan Mehmet Üniversitesi'), ('122', 'Haliç Üniversitesi'), ('123', 'İstanbul 29 Mayıs Üniversitesi'), ('124', 'İstanbul Arel Üniversitesi'), ('125', 'İstanbul Aydın Üniversitesi'), ('126', 'İstanbul Bilgi Üniversitesi'), ('127', 'İstanbul Gelişim Üniversitesi'), ('128', 'İstanbul Kemerburgaz Üniversitesi'), ('129', 'İstanbul Kültür Üniversitesi'), ('130', 'İstanbul Medipol Üniversitesi'), ('131', 'İstanbul Şehir Üniversitesi'), ('132', 'İstinye Üniversitesi'), ('132', 'İzmir Ekonomi Üniversitesi'), ('133', 'Kadir Has Üniversitesi'), ('134', 'Nişantaşı Üniversitesi'), ('135', 'Okan Üniversitesi'), ('136', 'Özyeğin Üniversitesi'), ('137', 'Piri Reis Üniversitesi'), ('138', 'Sabancı Üniversitesi'), ('139', 'TED Üniversitesi'), ('140', 'Yeditepe Üniversitesi')], default='Işık Üniversitesi', max_length=60, verbose_name='University')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Is Valid')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['program', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Code')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2019)], verbose_name='Year')),
            ],
            options={
                'ordering': ['program', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('dept_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campus.AcademicStaff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Institute Name')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_head', to='Campus.AcademicStaff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Course')),
                ('ccr_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.CcrCourse')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='ID Number')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('nationality', models.CharField(blank=True, max_length=15, verbose_name='Nationality')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('birth_place', models.CharField(blank=True, max_length=60, verbose_name='Birth Place')),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=10, verbose_name='Marital')),
                ('religion', models.CharField(blank=True, max_length=15, verbose_name='Religion')),
                ('blood_type', models.CharField(blank=True, choices=[('A Rh+', 'A Rh+'), ('B Rh+', 'B Rh+'), ('AB Rh+', 'AB Rh+'), ('0 Rh+', '0 Rh+'), ('A Rh-', 'A Rh-'), ('B Rh-', 'B Rh-'), ('AB Rh-', 'AB Rh-'), ('0 Rh-', '0 Rh-')], max_length=5, verbose_name='Blood Type')),
                ('province', models.CharField(blank=True, max_length=60, verbose_name='Province')),
                ('district', models.CharField(blank=True, max_length=60, verbose_name='District')),
                ('village', models.CharField(blank=True, max_length=60, verbose_name='Village')),
                ('registration_no', models.CharField(blank=True, max_length=4, verbose_name='Registration No')),
                ('family_no', models.CharField(blank=True, max_length=7, verbose_name='Family No')),
                ('order_no', models.CharField(blank=True, max_length=4, verbose_name='Order No')),
                ('mother_name', models.CharField(blank=True, max_length=60, verbose_name="Mother's Name")),
                ('father_name', models.CharField(blank=True, max_length=60, verbose_name="Father's Name")),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
                ('type', models.CharField(choices=[('Master', 'The Master of Science Program'), ('Doctoral', 'The Doctor of Philosophy Program')], max_length=60, verbose_name='Type')),
                ('thesis', models.BooleanField(default=False, verbose_name='Thesis')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Department')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prog_head', to='Campus.AcademicStaff')),
                ('quota_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campus.AcademicStaff')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday')], max_length=15, verbose_name='Section Day')),
                ('slot', models.CharField(choices=[('1', '17-18'), ('2', '18-19'), ('3', '19-20'), ('4', '20-21'), ('5', '21-22')], max_length=2, verbose_name='Section Slot')),
                ('place', models.CharField(choices=[('1', '101'), ('2', '102'), ('3', '103')], max_length=15, verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Course Schedule',
                'ordering': ['section', 'day', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Section Number')),
                ('year', models.CharField(default=2018, max_length=4, verbose_name='Year')),
                ('semester', models.CharField(choices=[('1', 'Summer'), ('2', 'Winter'), ('3', 'Spring')], max_length=10, verbose_name='Semester')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Course', verbose_name='Course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campus.AcademicStaff')),
            ],
            options={
                'ordering': ('course', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(max_length=11, unique=True, verbose_name='TC Number')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10, verbose_name='Gender')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('main_email', models.EmailField(max_length=254, unique=True, verbose_name='Main Email')),
                ('school_email', models.EmailField(max_length=254, unique=True, verbose_name='School Email')),
                ('address', models.TextField(max_length=60, null=True, verbose_name='Address')),
                ('city', models.CharField(choices=[('1', 'Adana'), ('2', 'Adıyaman'), ('3', 'Afyonkarahisar'), ('4', 'Ağrı'), ('5', 'Amasya'), ('6', 'Ankara'), ('7', 'Antalya'), ('8', 'Artvin'), ('9', 'Aydın'), ('10', 'Balıkesir'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bingöl'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkâri'), ('31', 'Hatay'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('66', 'Yozgat'), ('67', 'Zonguldak'), ('68', 'Aksaray'), ('69', 'Bayburt'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('72', 'Batman'), ('73', 'Şırnak'), ('74', 'Bartın'), ('75', 'Ardahan'), ('76', 'Iğdır'), ('77', 'Yalova'), ('78', 'Karabük'), ('79', 'Kilis'), ('80', 'Osmaniye'), ('81', 'Düzce')], max_length=20, verbose_name='City')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='Student ID')),
                ('st_email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='School Email Address')),
                ('hold_state', models.BooleanField(default=False, verbose_name='Hold State')),
                ('reg_open_statue', models.BooleanField(default=False, verbose_name='Registration Open Statue')),
                ('approval_statue', models.BooleanField(default=True, verbose_name='Approval Statue')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campus.AcademicStaff')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Curriculum')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Program')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Course')),
                ('ccr_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.CcrCourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Student')),
            ],
            options={
                'verbose_name': 'Taken Course',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(max_length=11, unique=True, verbose_name='TC Number')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10, verbose_name='Gender')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=60, verbose_name='Address')),
                ('city', models.CharField(choices=[('1', 'Adana'), ('2', 'Adıyaman'), ('3', 'Afyonkarahisar'), ('4', 'Ağrı'), ('5', 'Amasya'), ('6', 'Ankara'), ('7', 'Antalya'), ('8', 'Artvin'), ('9', 'Aydın'), ('10', 'Balıkesir'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bingöl'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkâri'), ('31', 'Hatay'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('66', 'Yozgat'), ('67', 'Zonguldak'), ('68', 'Aksaray'), ('69', 'Bayburt'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('72', 'Batman'), ('73', 'Şırnak'), ('74', 'Bartın'), ('75', 'Ardahan'), ('76', 'Iğdır'), ('77', 'Yalova'), ('78', 'Karabük'), ('79', 'Kilis'), ('80', 'Osmaniye'), ('81', 'Düzce')], max_length=20, verbose_name='City')),
                ('degree', models.CharField(choices=[('1', 'Bachelor'), ('2', 'Master'), ('3', 'Doctorate')], max_length=10, verbose_name='Degree')),
                ('university', models.CharField(choices=[('1', 'Işık Üniversitesi'), ('2', 'Abant İzzet Baysal Üniversitesi'), ('3', 'Adana Bilim ve Teknoloji Üniversitesi'), ('4', 'Adıyaman Üniversitesi'), ('5', 'Adnan Menderes Üniversitesi'), ('6', 'Afyon Kocatepe Üniversitesi'), ('7', 'Ağrı İbrahim Çeçen Üniversitesi'), ('8', 'Ahi Evran Üniversitesi'), ('9', 'Akdeniz Üniversitesi'), ('10', 'Aksaray Üniversitesi'), ('11', 'Alanya Alaaddin Keykubat Üniversitesi'), ('12', 'Amasya Üniversitesi'), ('13', 'Anadolu Üniversitesi'), ('14', 'Ankara Üniversitesi'), ('15', 'Ankara Sosyal Bilimler Üniversitesi'), ('16', 'Ardahan Üniversitesi'), ('17', 'Artvin Çoruh Üniversitesi'), ('18', 'Atatürk Üniversitesi'), ('19', 'Balıkesir Üniversitesi'), ('20', 'Bandırma Onyedi Eylül Üniversitesi'), ('21', 'Bartın Üniversitesi'), ('22', 'Batman Üniversitesi'), ('23', 'Bayburt Üniversitesi'), ('24', 'Bilecik Şeyh Edebali Üniversitesi'), ('25', 'Bingöl Üniversitesi'), ('26', 'Bitlis Eren Üniversitesi'), ('27', 'Boğaziçi Üniversitesi'), ('28', 'Bozok Üniversitesi'), ('29', 'Bursa Teknik Üniversitesi'), ('30', 'Celal Bayar Üniversitesi'), ('31', 'Cumhuriyet Üniversitesi'), ('32', 'Çanakkale Onsekiz Mart Üniversitesi'), ('33', 'Çankırı Karatekin Üniversitesi'), ('34', 'Çukurova Üniversitesi'), ('35', 'Deniz Harp Okulu'), ('36', 'Dicle Üniversitesi'), ('37', 'Dokuz Eylül Üniversitesi'), ('38', 'Dumlupınar Üniversitesi'), ('39', 'Düzce Üniversitesi'), ('40', 'Ege Üniversitesi'), ('41', 'Erciyes Üniversitesi'), ('42', 'Erzincan Üniversitesi'), ('43', 'Erzurum Teknik Üniversitesi'), ('44', 'Eskişehir Osmangazi Üniversitesi'), ('45', 'Fırat Üniversitesi'), ('46', 'Galatasaray Üniversitesi'), ('47', 'Gazi Üniversitesi'), ('48', 'Gaziantep Üniversitesi'), ('49', 'Gaziosmanpaşa Üniversitesi'), ('50', 'Gebze Teknik Üniversitesi'), ('51', 'Giresun Üniversitesi'), ('52', 'Gümüşhane Üniversitesi'), ('53', 'Hacettepe Üniversitesi'), ('54', 'Hakkari Üniversitesi'), ('55', 'Harran Üniversitesi'), ('56', 'Hava Harp Okulu'), ('57', 'Hitit Üniversitesi'), ('58', 'Iğdır Üniversitesi'), ('59', 'İnönü Üniversitesi'), ('60', 'İskenderun Teknik Üniversitesi'), ('61', 'İstanbul Medeniyet Üniversitesi'), ('62', 'İstanbul Üniversitesi'), ('63', 'İstanbul Teknik Üniversitesi'), ('64', 'İzmir Bakırçay Üniversitesi'), ('65', 'İzmir Demokrasi Üniversitesi'), ('66', 'İzmir Kâtip Çelebi Üniversitesi'), ('67', 'İzmir Yüksek Teknoloji Enstitüsü'), ('68', 'Kafkas Üniversitesi'), ('69', 'Kahramanmaraş Sütçü İmam Üniversitesi'), ('70', 'Karabük Üniversitesi'), ('71', 'Karadeniz Teknik Üniversitesi'), ('72', 'Karamanoğlu Mehmetbey Üniversitesi'), ('73', 'Kastamonu Üniversitesi'), ('74', 'Kırıkkale Üniversitesi'), ('75', 'Kilis 7 Aralık Üniversitesi'), ('76', 'Kocaeli Üniversitesi'), ('78', 'Necmettin Erbakan Üniversitesi'), ('79', 'Mardin Artuklu Üniversitesi'), ('80', 'Marmara Üniversitesi'), ('81', 'Mehmet Akif Ersoy Üniversitesi'), ('82', 'Mersin Üniversitesi'), ('83', 'Mimar Sinan Güzel Sanatlar Üniversitesi'), ('84', 'Muğla Sıtkı Koçman Üniversitesi'), ('85', 'Mustafa Kemal Üniversitesi'), ('86', 'Muş Alparslan Üniversitesi'), ('87', 'Namık Kemal Üniversitesi'), ('88', 'Nevşehir Hacı Bektaş Veli Üniversitesi'), ('89', 'Niğde Üniversitesi'), ('90', 'Ondokuz Mayıs Üniversitesi'), ('91', 'Ordu Üniversitesi'), ('92', 'Orta Doğu Teknik Üniversitesi'), ('93', 'Osmaniye Korkut Ata Üniversitesi'), ('94', 'Pamukkale Üniversitesi'), ('95', 'Sakarya Üniversitesi'), ('96', 'Selçuk Üniversitesi'), ('97', 'Siirt Üniversitesi'), ('98', 'Süleyman Demirel Üniversitesi'), ('99', 'Trakya Üniversitesi'), ('100', 'Uludağ Üniversitesi'), ('101', 'Uşak Üniversitesi'), ('102', 'Yalova Üniversitesi'), ('103', 'Yıldız Teknik Üniversitesi'), ('104', 'Yıldırım Beyazıt Üniversitesi'), ('105', 'Yüzüncü Yıl Üniversitesi'), ('106', 'Bülent Ecevit Üniversitesi'), ('107', 'Acıbadem Üniversitesi'), ('108', 'Akev Üniversitesi'), ('109', 'Anka Teknoloji Üniversitesi'), ('110', 'Atılım Üniversitesi'), ('111', 'Avrasya Üniversitesi'), ('112', 'Bahçeşehir Üniversitesi'), ('113', 'Başkent Üniversitesi'), ('114', 'Beykent Üniversitesi'), ('115', 'Bezmiâlem Vakıf Üniversitesi'), ('116', 'Bilkent Üniversitesi'), ('117', 'Biruni Üniversitesi'), ('118', 'Çankaya Üniversitesi'), ('119', 'Çağ Üniversitesi'), ('120', 'Doğuş Üniversitesi'), ('121', 'Fatih Sultan Mehmet Üniversitesi'), ('122', 'Haliç Üniversitesi'), ('123', 'İstanbul 29 Mayıs Üniversitesi'), ('124', 'İstanbul Arel Üniversitesi'), ('125', 'İstanbul Aydın Üniversitesi'), ('126', 'İstanbul Bilgi Üniversitesi'), ('127', 'İstanbul Gelişim Üniversitesi'), ('128', 'İstanbul Kemerburgaz Üniversitesi'), ('129', 'İstanbul Kültür Üniversitesi'), ('130', 'İstanbul Medipol Üniversitesi'), ('131', 'İstanbul Şehir Üniversitesi'), ('132', 'İstinye Üniversitesi'), ('132', 'İzmir Ekonomi Üniversitesi'), ('133', 'Kadir Has Üniversitesi'), ('134', 'Nişantaşı Üniversitesi'), ('135', 'Okan Üniversitesi'), ('136', 'Özyeğin Üniversitesi'), ('137', 'Piri Reis Üniversitesi'), ('138', 'Sabancı Üniversitesi'), ('139', 'TED Üniversitesi'), ('140', 'Yeditepe Üniversitesi')], max_length=50, verbose_name='University')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='GPA')),
                ('ales', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='ALES')),
                ('yds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)], verbose_name='YDS')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Program')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+905304440044"', regex='^\\+(?:[0-9] ?){6,14}[0-9]$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('personal_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campus.PersonalInformation')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', Campus.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='section',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='Campus.Section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Institute'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Program'),
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='act_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Course'),
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='ccr_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.CcrCourse'),
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Student'),
        ),
        migrations.AddField(
            model_name='ccrcourse',
            name='ccr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Curriculum'),
        ),
        migrations.AddField(
            model_name='ccrcourse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.CourseType'),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campus.Institute'),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Campus.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='takencourse',
            unique_together={('student', 'ccr_course', 'act_course')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('section', 'day', 'slot')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('code', 'type', 'thesis')},
        ),
        migrations.AlterUniqueTogether(
            name='offeredcourse',
            unique_together={('ccr_course', 'act_course')},
        ),
        migrations.AlterUniqueTogether(
            name='completedcourse',
            unique_together={('student', 'ccr_course', 'act_course')},
        ),
        migrations.AlterUniqueTogether(
            name='ccrcourse',
            unique_together={('ccr', 'type', 'no')},
        ),
    ]
