# Generated by Django 2.0.4 on 2018-04-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Campus.Department'),
        ),
    ]
