# Generated by Django 2.0.4 on 2018-04-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0003_auto_20180406_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='head',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Campus.AcademicStaff'),
        ),
    ]
