# Generated by Django 2.0.4 on 2018-04-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0004_auto_20180406_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Firday')], max_length=20, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place',
            field=models.CharField(choices=[('1', '101'), ('2', '102'), ('3', '103')], max_length=40, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('1', '17-18'), ('2', '18-19'), ('3', '19-20'), ('4', '20-21'), ('5', '21-22')], max_length=20, null=True, verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='degree',
            field=models.CharField(choices=[('1', 'Bachelor'), ('2', 'Master'), ('3', 'Doctorate')], default='Lisans', max_length=20, verbose_name='Degree'),
        ),
    ]
