# Generated by Django 2.0.3 on 2018-04-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('code', 'type')},
        ),
    ]
