# Generated by Django 2.0.3 on 2018-04-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20180408_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitorprogram',
            unique_together={('visitor', 'program')},
        ),
    ]
