# Generated by Django 2.0.3 on 2018-04-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20180408_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='main_email',
        ),
    ]
