# Generated by Django 2.0.3 on 2018-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_remove_staff_main_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='city',
        ),
    ]
