# Generated by Django 2.0.3 on 2018-04-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20180409_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='st_id',
        ),
    ]
