# Generated by Django 2.0.3 on 2018-04-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_remove_student_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedcourse',
            name='act_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Section'),
        ),
        migrations.AlterField(
            model_name='takencourse',
            name='act_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Section'),
        ),
    ]
