# Generated by Django 2.0.4 on 2018-04-11 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_ccrcourse_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccrcourse',
            name='credit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Credit'),
        ),
    ]
