# Generated by Django 2.0.4 on 2018-04-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_auto_20180412_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=15, verbose_name='Section Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[(1, '9-10'), (2, '10-11'), (3, '11-12'), (4, '12-13'), (5, '13-14'), (6, '14-15'), (7, '15-16'), (8, '16-17'), (9, '17-18'), (10, '18-19'), (11, '19-20'), (12, '20-21'), (13, '21-22')], max_length=2, verbose_name='Section Slot'),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('1', 'Summer'), ('2', 'Fall'), ('3', 'Spring')], max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='completedcourse',
            unique_together={('student', 'ccr_course')},
        ),
    ]
