# Generated by Django 2.0.4 on 2018-04-21 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_auto_20180414_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='quota',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quota'),
        ),
        migrations.AlterField(
            model_name='ccrcourse',
            name='no',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='completedcourse',
            name='grade',
            field=models.CharField(choices=[('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('F', 'F'), ('W', 'W')], max_length=2, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=15, verbose_name='Section Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place',
            field=models.CharField(choices=[('1', 'DMF-101'), ('2', 'DMF-102'), ('3', 'DMF-103')], max_length=15, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('1', '9-10'), ('2', '10-11'), ('3', '11-12'), ('4', '12-13'), ('5', '13-14'), ('6', '14-15'), ('7', '15-16'), ('8', '16-17'), ('9', '17-18'), ('10', '18-19'), ('11', '19-20'), ('12', '20-21'), ('13', '21-22')], max_length=2, verbose_name='Section Slot'),
        ),
    ]
