# Generated by Django 2.0.4 on 2018-05-01 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_auto_20180502_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='id_number',
            field=models.CharField(max_length=11, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
