# Generated by Django 2.0.4 on 2018-06-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0018_auto_20180604_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Curriculum'),
        ),
    ]
