# Generated by Django 2.0.4 on 2018-06-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0019_student_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Program'),
        ),
    ]
