# Generated by Django 2.0.4 on 2018-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0020_visitor_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
