# Generated by Django 2.0.3 on 2018-03-21 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=15, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('tcNumber', models.CharField(max_length=11, unique=True, verbose_name='TC Number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Man')], default='Kadın', max_length=5, verbose_name='Sex')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Address')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(choices=[('1', 'Adana'), ('2', 'Adıyaman'), ('3', 'Afyonkarahisar'), ('4', 'Ağrı'), ('5', 'Amasya'), ('6', 'Ankara'), ('7', 'Antalya'), ('8', 'Artvin'), ('9', 'Aydın'), ('10', 'Balıkesir'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bingöl'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkâri'), ('31', 'Hatay'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('66', 'Yozgat'), ('67', 'Zonguldak'), ('68', 'Aksaray'), ('69', 'Bayburt'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('72', 'Batman'), ('73', 'Şırnak'), ('74', 'Bartın'), ('75', 'Ardahan'), ('76', 'Iğdır'), ('77', 'Yalova'), ('78', 'Karabük'), ('79', 'Kilis'), ('80', 'Osmaniye'), ('81', 'Düzce')], default='İstanbul', max_length=20, verbose_name='Current city')),
                ('phoneNumber', models.CharField(default='Phone Number', max_length=11, unique=True, verbose_name='Phone Number')),
                ('ssn', models.CharField(default='SSN', max_length=11, unique=True, verbose_name='SSN')),
            ],
            options={
                'verbose_name_plural': 'Academic Instructors',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=15, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('tcNumber', models.CharField(max_length=11, unique=True, verbose_name='TC Number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Man')], default='Female', max_length=5, verbose_name='Sex')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Address')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(choices=[('1', 'Adana'), ('2', 'Adıyaman'), ('3', 'Afyonkarahisar'), ('4', 'Ağrı'), ('5', 'Amasya'), ('6', 'Ankara'), ('7', 'Antalya'), ('8', 'Artvin'), ('9', 'Aydın'), ('10', 'Balıkesir'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bingöl'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkâri'), ('31', 'Hatay'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('66', 'Yozgat'), ('67', 'Zonguldak'), ('68', 'Aksaray'), ('69', 'Bayburt'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('72', 'Batman'), ('73', 'Şırnak'), ('74', 'Bartın'), ('75', 'Ardahan'), ('76', 'Iğdır'), ('77', 'Yalova'), ('78', 'Karabük'), ('79', 'Kilis'), ('80', 'Osmaniye'), ('81', 'Düzce')], default='İstanbul', max_length=20, verbose_name='Current city')),
                ('phoneNumber', models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='Phone Number')),
                ('degree', models.CharField(choices=[('1', 'Lisans'), ('2', 'Yüksek Lisans'), ('3', 'Doktora')], default='Lisans', max_length=20, verbose_name='Degree')),
                ('university', models.CharField(choices=[('1', 'Işık Üniversitesi'), ('2', 'Abant İzzet Baysal Üniversitesi'), ('3', 'Adana Bilim ve Teknoloji Üniversitesi'), ('4', 'Adıyaman Üniversitesi'), ('5', 'Adnan Menderes Üniversitesi'), ('6', 'Afyon Kocatepe Üniversitesi'), ('7', 'Ağrı İbrahim Çeçen Üniversitesi'), ('8', 'Ahi Evran Üniversitesi'), ('9', 'Akdeniz Üniversitesi'), ('10', 'Aksaray Üniversitesi'), ('11', 'Alanya Alaaddin Keykubat Üniversitesi'), ('12', 'Amasya Üniversitesi'), ('13', 'Anadolu Üniversitesi'), ('14', 'Ankara Üniversitesi'), ('15', 'Ankara Sosyal Bilimler Üniversitesi'), ('16', 'Ardahan Üniversitesi'), ('17', 'Artvin Çoruh Üniversitesi'), ('18', 'Atatürk Üniversitesi'), ('19', 'Balıkesir Üniversitesi'), ('20', 'Bandırma Onyedi Eylül Üniversitesi'), ('21', 'Bartın Üniversitesi'), ('22', 'Batman Üniversitesi'), ('23', 'Bayburt Üniversitesi'), ('24', 'Bilecik Şeyh Edebali Üniversitesi'), ('25', 'Bingöl Üniversitesi'), ('26', 'Bitlis Eren Üniversitesi'), ('27', 'Boğaziçi Üniversitesi'), ('28', 'Bozok Üniversitesi'), ('29', 'Bursa Teknik Üniversitesi'), ('30', 'Celal Bayar Üniversitesi'), ('31', 'Cumhuriyet Üniversitesi'), ('32', 'Çanakkale Onsekiz Mart Üniversitesi'), ('33', 'Çankırı Karatekin Üniversitesi'), ('34', 'Çukurova Üniversitesi'), ('35', 'Deniz Harp Okulu'), ('36', 'Dicle Üniversitesi'), ('37', 'Dokuz Eylül Üniversitesi'), ('38', 'Dumlupınar Üniversitesi'), ('39', 'Düzce Üniversitesi'), ('40', 'Ege Üniversitesi'), ('41', 'Erciyes Üniversitesi'), ('42', 'Erzincan Üniversitesi'), ('43', 'Erzurum Teknik Üniversitesi'), ('44', 'Eskişehir Osmangazi Üniversitesi'), ('45', 'Fırat Üniversitesi'), ('46', 'Galatasaray Üniversitesi'), ('47', 'Gazi Üniversitesi'), ('48', 'Gaziantep Üniversitesi'), ('49', 'Gaziosmanpaşa Üniversitesi'), ('50', 'Gebze Teknik Üniversitesi'), ('51', 'Giresun Üniversitesi'), ('52', 'Gümüşhane Üniversitesi'), ('53', 'Hacettepe Üniversitesi'), ('54', 'Hakkari Üniversitesi'), ('55', 'Harran Üniversitesi'), ('56', 'Hava Harp Okulu'), ('57', 'Hitit Üniversitesi'), ('58', 'Iğdır Üniversitesi'), ('59', 'İnönü Üniversitesi'), ('60', 'İskenderun Teknik Üniversitesi'), ('61', 'İstanbul Medeniyet Üniversitesi'), ('62', 'İstanbul Üniversitesi'), ('63', 'İstanbul Teknik Üniversitesi'), ('64', 'İzmir Bakırçay Üniversitesi'), ('65', 'İzmir Demokrasi Üniversitesi'), ('66', 'İzmir Kâtip Çelebi Üniversitesi'), ('67', 'İzmir Yüksek Teknoloji Enstitüsü'), ('68', 'Kafkas Üniversitesi'), ('69', 'Kahramanmaraş Sütçü İmam Üniversitesi'), ('70', 'Karabük Üniversitesi'), ('71', 'Karadeniz Teknik Üniversitesi'), ('72', 'Karamanoğlu Mehmetbey Üniversitesi'), ('73', 'Kastamonu Üniversitesi'), ('74', 'Kırıkkale Üniversitesi'), ('75', 'Kilis 7 Aralık Üniversitesi'), ('76', 'Kocaeli Üniversitesi'), ('78', 'Necmettin Erbakan Üniversitesi'), ('79', 'Mardin Artuklu Üniversitesi'), ('80', 'Marmara Üniversitesi'), ('81', 'Mehmet Akif Ersoy Üniversitesi'), ('82', 'Mersin Üniversitesi'), ('83', 'Mimar Sinan Güzel Sanatlar Üniversitesi'), ('84', 'Muğla Sıtkı Koçman Üniversitesi'), ('85', 'Mustafa Kemal Üniversitesi'), ('86', 'Muş Alparslan Üniversitesi'), ('87', 'Namık Kemal Üniversitesi'), ('88', 'Nevşehir Hacı Bektaş Veli Üniversitesi'), ('89', 'Niğde Üniversitesi'), ('90', 'Ondokuz Mayıs Üniversitesi'), ('91', 'Ordu Üniversitesi'), ('92', 'Orta Doğu Teknik Üniversitesi'), ('93', 'Osmaniye Korkut Ata Üniversitesi'), ('94', 'Pamukkale Üniversitesi'), ('95', 'Sakarya Üniversitesi'), ('96', 'Selçuk Üniversitesi'), ('97', 'Siirt Üniversitesi'), ('98', 'Süleyman Demirel Üniversitesi'), ('99', 'Trakya Üniversitesi'), ('100', 'Uludağ Üniversitesi'), ('101', 'Uşak Üniversitesi'), ('102', 'Yalova Üniversitesi'), ('103', 'Yıldız Teknik Üniversitesi'), ('104', 'Yıldırım Beyazıt Üniversitesi'), ('105', 'Yüzüncü Yıl Üniversitesi'), ('106', 'Bülent Ecevit Üniversitesi'), ('107', 'Acıbadem Üniversitesi'), ('108', 'Akev Üniversitesi'), ('109', 'Anka Teknoloji Üniversitesi'), ('110', 'Atılım Üniversitesi'), ('111', 'Avrasya Üniversitesi'), ('112', 'Bahçeşehir Üniversitesi'), ('113', 'Başkent Üniversitesi'), ('114', 'Beykent Üniversitesi'), ('115', 'Bezmiâlem Vakıf Üniversitesi'), ('116', 'Bilkent Üniversitesi'), ('117', 'Biruni Üniversitesi'), ('118', 'Çankaya Üniversitesi'), ('119', 'Çağ Üniversitesi'), ('120', 'Doğuş Üniversitesi'), ('121', 'Fatih Sultan Mehmet Üniversitesi'), ('122', 'Haliç Üniversitesi'), ('123', 'İstanbul 29 Mayıs Üniversitesi'), ('124', 'İstanbul Arel Üniversitesi'), ('125', 'İstanbul Aydın Üniversitesi'), ('126', 'İstanbul Bilgi Üniversitesi'), ('127', 'İstanbul Gelişim Üniversitesi'), ('128', 'İstanbul Kemerburgaz Üniversitesi'), ('129', 'İstanbul Kültür Üniversitesi'), ('130', 'İstanbul Medipol Üniversitesi'), ('131', 'İstanbul Şehir Üniversitesi'), ('132', 'İstinye Üniversitesi'), ('132', 'İzmir Ekonomi Üniversitesi'), ('133', 'Kadir Has Üniversitesi'), ('134', 'Nişantaşı Üniversitesi'), ('135', 'Okan Üniversitesi'), ('136', 'Özyeğin Üniversitesi'), ('137', 'Piri Reis Üniversitesi'), ('138', 'Sabancı Üniversitesi'), ('139', 'TED Üniversitesi'), ('140', 'Yeditepe Üniversitesi')], default='Işık Üniversitesi', max_length=50, verbose_name='University')),
                ('gpa', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='General Point Average')),
                ('scienceExam', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='ALES Point')),
                ('foreignLanguageExam', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='YDS Point')),
                ('program', models.CharField(choices=[('cse', 'CSE'), ('se', 'SE')], default='cse', max_length=40, verbose_name='Program')),
            ],
            options={
                'verbose_name_plural': 'Applies',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(choices=[(1, '234'), (2, '500')], max_length=6, null=True, verbose_name='Class Name')),
                ('date', models.CharField(choices=[(1, '234'), (2, '670')], max_length=6, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Code', max_length=3, unique=True, verbose_name='Code')),
                ('definition', models.CharField(default='Definition', max_length=50, verbose_name='Definition')),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='Year')),
                ('semester', models.CharField(choices=[('1', 'Fall'), ('2', 'Spring'), ('3', 'Summer')], max_length=6, verbose_name='Semester')),
                ('credit', models.PositiveSmallIntegerField(null=True, verbose_name='Credit')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Code', max_length=3, unique=True, verbose_name='Code')),
                ('definition', models.CharField(default='Definition', max_length=50, verbose_name='Definition')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formID', models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Form ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True, verbose_name='Title')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Descriptipn')),
                ('helloo', models.URLField(unique=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='GrandStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15, null=True, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=15, null=True, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=15, null=True, verbose_name='Last Name')),
                ('joinedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('tcNumber', models.CharField(max_length=11, unique=True, verbose_name='TC Number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Man')], default='Kadın', max_length=5, verbose_name='Sex')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Address')),
                ('address', models.CharField(max_length=40, null=True, verbose_name='Address')),
                ('city', models.CharField(choices=[('1', 'Adana'), ('2', 'Adıyaman'), ('3', 'Afyonkarahisar'), ('4', 'Ağrı'), ('5', 'Amasya'), ('6', 'Ankara'), ('7', 'Antalya'), ('8', 'Artvin'), ('9', 'Aydın'), ('10', 'Balıkesir'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bingöl'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkâri'), ('31', 'Hatay'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('66', 'Yozgat'), ('67', 'Zonguldak'), ('68', 'Aksaray'), ('69', 'Bayburt'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('72', 'Batman'), ('73', 'Şırnak'), ('74', 'Bartın'), ('75', 'Ardahan'), ('76', 'Iğdır'), ('77', 'Yalova'), ('78', 'Karabük'), ('79', 'Kilis'), ('80', 'Osmaniye'), ('81', 'Düzce')], default='İstanbul', max_length=20, verbose_name='Current city')),
                ('phoneNumber', models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='Phone Number')),
                ('degree', models.CharField(choices=[('1', 'Lisans'), ('2', 'Yüksek Lisans'), ('3', 'Doktora')], default='Lisans', max_length=20, verbose_name='Degree')),
                ('university', models.CharField(choices=[('1', 'Işık Üniversitesi'), ('2', 'Abant İzzet Baysal Üniversitesi'), ('3', 'Adana Bilim ve Teknoloji Üniversitesi'), ('4', 'Adıyaman Üniversitesi'), ('5', 'Adnan Menderes Üniversitesi'), ('6', 'Afyon Kocatepe Üniversitesi'), ('7', 'Ağrı İbrahim Çeçen Üniversitesi'), ('8', 'Ahi Evran Üniversitesi'), ('9', 'Akdeniz Üniversitesi'), ('10', 'Aksaray Üniversitesi'), ('11', 'Alanya Alaaddin Keykubat Üniversitesi'), ('12', 'Amasya Üniversitesi'), ('13', 'Anadolu Üniversitesi'), ('14', 'Ankara Üniversitesi'), ('15', 'Ankara Sosyal Bilimler Üniversitesi'), ('16', 'Ardahan Üniversitesi'), ('17', 'Artvin Çoruh Üniversitesi'), ('18', 'Atatürk Üniversitesi'), ('19', 'Balıkesir Üniversitesi'), ('20', 'Bandırma Onyedi Eylül Üniversitesi'), ('21', 'Bartın Üniversitesi'), ('22', 'Batman Üniversitesi'), ('23', 'Bayburt Üniversitesi'), ('24', 'Bilecik Şeyh Edebali Üniversitesi'), ('25', 'Bingöl Üniversitesi'), ('26', 'Bitlis Eren Üniversitesi'), ('27', 'Boğaziçi Üniversitesi'), ('28', 'Bozok Üniversitesi'), ('29', 'Bursa Teknik Üniversitesi'), ('30', 'Celal Bayar Üniversitesi'), ('31', 'Cumhuriyet Üniversitesi'), ('32', 'Çanakkale Onsekiz Mart Üniversitesi'), ('33', 'Çankırı Karatekin Üniversitesi'), ('34', 'Çukurova Üniversitesi'), ('35', 'Deniz Harp Okulu'), ('36', 'Dicle Üniversitesi'), ('37', 'Dokuz Eylül Üniversitesi'), ('38', 'Dumlupınar Üniversitesi'), ('39', 'Düzce Üniversitesi'), ('40', 'Ege Üniversitesi'), ('41', 'Erciyes Üniversitesi'), ('42', 'Erzincan Üniversitesi'), ('43', 'Erzurum Teknik Üniversitesi'), ('44', 'Eskişehir Osmangazi Üniversitesi'), ('45', 'Fırat Üniversitesi'), ('46', 'Galatasaray Üniversitesi'), ('47', 'Gazi Üniversitesi'), ('48', 'Gaziantep Üniversitesi'), ('49', 'Gaziosmanpaşa Üniversitesi'), ('50', 'Gebze Teknik Üniversitesi'), ('51', 'Giresun Üniversitesi'), ('52', 'Gümüşhane Üniversitesi'), ('53', 'Hacettepe Üniversitesi'), ('54', 'Hakkari Üniversitesi'), ('55', 'Harran Üniversitesi'), ('56', 'Hava Harp Okulu'), ('57', 'Hitit Üniversitesi'), ('58', 'Iğdır Üniversitesi'), ('59', 'İnönü Üniversitesi'), ('60', 'İskenderun Teknik Üniversitesi'), ('61', 'İstanbul Medeniyet Üniversitesi'), ('62', 'İstanbul Üniversitesi'), ('63', 'İstanbul Teknik Üniversitesi'), ('64', 'İzmir Bakırçay Üniversitesi'), ('65', 'İzmir Demokrasi Üniversitesi'), ('66', 'İzmir Kâtip Çelebi Üniversitesi'), ('67', 'İzmir Yüksek Teknoloji Enstitüsü'), ('68', 'Kafkas Üniversitesi'), ('69', 'Kahramanmaraş Sütçü İmam Üniversitesi'), ('70', 'Karabük Üniversitesi'), ('71', 'Karadeniz Teknik Üniversitesi'), ('72', 'Karamanoğlu Mehmetbey Üniversitesi'), ('73', 'Kastamonu Üniversitesi'), ('74', 'Kırıkkale Üniversitesi'), ('75', 'Kilis 7 Aralık Üniversitesi'), ('76', 'Kocaeli Üniversitesi'), ('78', 'Necmettin Erbakan Üniversitesi'), ('79', 'Mardin Artuklu Üniversitesi'), ('80', 'Marmara Üniversitesi'), ('81', 'Mehmet Akif Ersoy Üniversitesi'), ('82', 'Mersin Üniversitesi'), ('83', 'Mimar Sinan Güzel Sanatlar Üniversitesi'), ('84', 'Muğla Sıtkı Koçman Üniversitesi'), ('85', 'Mustafa Kemal Üniversitesi'), ('86', 'Muş Alparslan Üniversitesi'), ('87', 'Namık Kemal Üniversitesi'), ('88', 'Nevşehir Hacı Bektaş Veli Üniversitesi'), ('89', 'Niğde Üniversitesi'), ('90', 'Ondokuz Mayıs Üniversitesi'), ('91', 'Ordu Üniversitesi'), ('92', 'Orta Doğu Teknik Üniversitesi'), ('93', 'Osmaniye Korkut Ata Üniversitesi'), ('94', 'Pamukkale Üniversitesi'), ('95', 'Sakarya Üniversitesi'), ('96', 'Selçuk Üniversitesi'), ('97', 'Siirt Üniversitesi'), ('98', 'Süleyman Demirel Üniversitesi'), ('99', 'Trakya Üniversitesi'), ('100', 'Uludağ Üniversitesi'), ('101', 'Uşak Üniversitesi'), ('102', 'Yalova Üniversitesi'), ('103', 'Yıldız Teknik Üniversitesi'), ('104', 'Yıldırım Beyazıt Üniversitesi'), ('105', 'Yüzüncü Yıl Üniversitesi'), ('106', 'Bülent Ecevit Üniversitesi'), ('107', 'Acıbadem Üniversitesi'), ('108', 'Akev Üniversitesi'), ('109', 'Anka Teknoloji Üniversitesi'), ('110', 'Atılım Üniversitesi'), ('111', 'Avrasya Üniversitesi'), ('112', 'Bahçeşehir Üniversitesi'), ('113', 'Başkent Üniversitesi'), ('114', 'Beykent Üniversitesi'), ('115', 'Bezmiâlem Vakıf Üniversitesi'), ('116', 'Bilkent Üniversitesi'), ('117', 'Biruni Üniversitesi'), ('118', 'Çankaya Üniversitesi'), ('119', 'Çağ Üniversitesi'), ('120', 'Doğuş Üniversitesi'), ('121', 'Fatih Sultan Mehmet Üniversitesi'), ('122', 'Haliç Üniversitesi'), ('123', 'İstanbul 29 Mayıs Üniversitesi'), ('124', 'İstanbul Arel Üniversitesi'), ('125', 'İstanbul Aydın Üniversitesi'), ('126', 'İstanbul Bilgi Üniversitesi'), ('127', 'İstanbul Gelişim Üniversitesi'), ('128', 'İstanbul Kemerburgaz Üniversitesi'), ('129', 'İstanbul Kültür Üniversitesi'), ('130', 'İstanbul Medipol Üniversitesi'), ('131', 'İstanbul Şehir Üniversitesi'), ('132', 'İstinye Üniversitesi'), ('132', 'İzmir Ekonomi Üniversitesi'), ('133', 'Kadir Has Üniversitesi'), ('134', 'Nişantaşı Üniversitesi'), ('135', 'Okan Üniversitesi'), ('136', 'Özyeğin Üniversitesi'), ('137', 'Piri Reis Üniversitesi'), ('138', 'Sabancı Üniversitesi'), ('139', 'TED Üniversitesi'), ('140', 'Yeditepe Üniversitesi')], default='Işık Üniversitesi', max_length=50, verbose_name='University')),
                ('gpa', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='General Point Average')),
                ('scienceExam', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='ALES Point')),
                ('foreignLanguageExam', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='YDS Point')),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Statue')),
                ('scholarship', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Scholarship')),
                ('studentID', models.CharField(max_length=9, unique=True, verbose_name='Student ID')),
                ('startingDate', models.DateField(default='2018-03-23', verbose_name='Starting Date')),
                ('endingDate', models.DateField(default='2018-03-23', verbose_name='Ending Date')),
                ('gpaI', models.PositiveSmallIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='GPA')),
                ('completedCredit', models.CharField(default='0', max_length=3, verbose_name='Completed Credit')),
            ],
            options={
                'verbose_name_plural': 'Grand Students',
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Head of Departments',
            },
        ),
        migrations.CreateModel(
            name='InstituteStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=15, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('tcNumber', models.CharField(max_length=11, unique=True, verbose_name='TC Number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Man')], default='Kadın', max_length=5, verbose_name='Sex')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Address')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(choices=[('1', 'Adana'), ('2', 'Adıyaman'), ('3', 'Afyonkarahisar'), ('4', 'Ağrı'), ('5', 'Amasya'), ('6', 'Ankara'), ('7', 'Antalya'), ('8', 'Artvin'), ('9', 'Aydın'), ('10', 'Balıkesir'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bingöl'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkâri'), ('31', 'Hatay'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('66', 'Yozgat'), ('67', 'Zonguldak'), ('68', 'Aksaray'), ('69', 'Bayburt'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('72', 'Batman'), ('73', 'Şırnak'), ('74', 'Bartın'), ('75', 'Ardahan'), ('76', 'Iğdır'), ('77', 'Yalova'), ('78', 'Karabük'), ('79', 'Kilis'), ('80', 'Osmaniye'), ('81', 'Düzce')], default='İstanbul', max_length=20, verbose_name='Current city')),
                ('phoneNumber', models.CharField(default='Phone Number', max_length=11, unique=True, verbose_name='Phone Number')),
                ('startingDate', models.DateTimeField(null=True, verbose_name='Starting Date')),
                ('ssn', models.CharField(default='SSN', max_length=11, unique=True, verbose_name='SSN')),
            ],
            options={
                'verbose_name_plural': 'Institute Staffs',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fullname', to='Institute.AcademicInstructor', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Instructor List',
            },
        ),
        migrations.CreateModel(
            name='OpenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='Institute.Course')),
                ('placeAndDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeAndDate', to='Institute.Classes')),
            ],
            options={
                'verbose_name_plural': 'Open Courses',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=50, unique=True, verbose_name='Name')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='Institute.Department')),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.PositiveSmallIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Report ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True, verbose_name='Title')),
                ('content', models.CharField(max_length=2000, null=True, verbose_name='Content')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link (if exists)')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Supervisior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicInstructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academicInstructor', to='Institute.Instructor')),
                ('grandS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grandS', to='Institute.GrandStudent', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Supervisiors',
            },
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Institute.Course')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program2', to='Institute.Program')),
            ],
            options={
                'verbose_name_plural': 'Taken Courses',
            },
        ),
        migrations.CreateModel(
            name='WeeklyScheduleI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseID', to='Institute.Course')),
                ('instructorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructorID', to='Institute.Course')),
            ],
            options={
                'verbose_name_plural': 'Weekly Schedules for Instructors',
            },
        ),
        migrations.CreateModel(
            name='WeeklyScheduleS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NameOfCourse', to='Institute.OpenCourse')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IDofStudent', to='Institute.GrandStudent')),
            ],
            options={
                'verbose_name_plural': 'Weekly Schedules for Students',
            },
        ),
        migrations.AddField(
            model_name='opencourse',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program3', to='Institute.Program'),
        ),
        migrations.AddField(
            model_name='head',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstName', to='Institute.Instructor', unique=True),
        ),
        migrations.AddField(
            model_name='grandstudent',
            name='academicSupervisior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academicSupervisior', to='Institute.Instructor'),
        ),
        migrations.AddField(
            model_name='grandstudent',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program4', to='Institute.Program'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='Institute.Head', unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='Institute.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program1', to='Institute.Program'),
        ),
    ]
