# Generated by Django 2.0.3 on 2018-03-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0003_auto_20180321_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceText', models.CharField(max_length=140, null=True, verbose_name='Choice Text')),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Choices for Questions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=140, null=True, verbose_name='Question Text')),
                ('publishedDate', models.DateTimeField(verbose_name='Published Date')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AlterModelOptions(
            name='pushnotificationistostudents',
            options={'verbose_name_plural': 'Push Notifications from Institute to Students'},
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Question'),
        ),
    ]
