# Generated by Django 2.0.3 on 2018-03-21 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0004_auto_20180321_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2018, max_length=4, unique=True, verbose_name='Year')),
                ('period', models.CharField(choices=[('1', 'Fall'), ('2', 'Spring'), ('3', 'Summer')], max_length=6, null=True, verbose_name='Period')),
            ],
            options={
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AlterField(
            model_name='grandstudent',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Statue'),
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date', to='Institute.Semester'),
        ),
    ]
