# Generated by Django 2.0.3 on 2018-03-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0005_auto_20180321_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=2018, max_length=4, verbose_name='Year'),
        ),
    ]
