# Generated by Django 2.0.3 on 2018-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0006_auto_20180321_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.PositiveSmallIntegerField(default=3, null=True, verbose_name='Credit'),
        ),
    ]
