# Generated by Django 2.0.3 on 2018-03-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0007_auto_20180321_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandstudent',
            name='militaryStatue',
            field=models.CharField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default='No', max_length=3, verbose_name='Military Statue'),
        ),
    ]
