# Generated by Django 2.0.3 on 2018-03-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0008_grandstudent_militarystatue'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandstudent',
            name='transcript',
            field=models.URLField(null=True, unique=True, verbose_name='Transcript Link'),
        ),
    ]
