# Generated by Django 2.0.3 on 2018-03-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0009_grandstudent_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'CCRs',
            },
        ),
        migrations.CreateModel(
            name='RequestOpenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(blank=True, default='0', max_length=1, null=True, verbose_name='Approval')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOpenCourse.course+', to='Institute.Course')),
                ('instructorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOpenCourse.instructorID+', to='Institute.Instructor')),
                ('placeAndDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOpenCourse.placeAndDate+', to='Institute.Classes')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOpenCourse.program+', to='Institute.Program')),
            ],
            options={
                'verbose_name_plural': 'Requests to Course',
            },
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='Institute.RequestOpenCourse'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='placeAndDate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeAndDate+', to='Institute.RequestOpenCourse'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program3', to='Institute.RequestOpenCourse'),
        ),
    ]
