# Generated by Django 2.0.3 on 2018-03-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0011_auto_20180322_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.CharField(choices=[('1', '234'), ('2', '670')], max_length=6, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='grandstudent',
            name='militaryStatue',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], default='No', max_length=3, verbose_name='Military Statue'),
        ),
    ]
