# Generated by Django 2.0.3 on 2018-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0012_auto_20180322_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='className',
            field=models.CharField(choices=[('1', '234'), ('2', '500')], max_length=6, null=True, unique=True, verbose_name='Class Name'),
        ),
    ]
