# Generated by Django 2.0.3 on 2018-03-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0013_auto_20180322_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='opencourse',
            name='approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OpenCourse.approval+', to='Institute.RequestOpenCourse'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='className',
            field=models.CharField(choices=[('1', '234'), ('2', '500')], max_length=6, null=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='period',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6, null=True, verbose_name='Period'),
        ),
    ]
