# Generated by Django 2.0.3 on 2018-03-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0014_auto_20180322_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requestopencourse',
            name='placeAndDate',
        ),
        migrations.AddField(
            model_name='classes',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='classes',
            name='timeIntervals',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=3, null=True, verbose_name='Time Intervals'),
        ),
        migrations.AddField(
            model_name='requestopencourse',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOpenCourse.day+', to='Institute.Classes'),
        ),
    ]
