# Generated by Django 2.0.3 on 2018-03-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0015_auto_20180322_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, null=True, unique=True, verbose_name='Class No')),
            ],
            options={
                'verbose_name_plural': 'Building Schema',
            },
        ),
        migrations.AlterField(
            model_name='classes',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.BuildingSchema'),
        ),
    ]
