# Generated by Django 2.0.3 on 2018-03-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0016_auto_20180322_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestopencourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOpenCourse.course+', to='Institute.TakenCourse'),
        ),
    ]
