# Generated by Django 2.0.3 on 2018-03-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0018_auto_20180322_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencourse',
            name='placeAndDate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes+', to='Institute.Classes'),
        ),
    ]
