# Generated by Django 2.0.3 on 2018-03-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0019_auto_20180322_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutestaff',
            name='startingDate',
        ),
        migrations.AddField(
            model_name='academicinstructor',
            name='startingDate',
            field=models.DateTimeField(null=True, verbose_name='Starting Date'),
        ),
    ]
