# Generated by Django 2.0.3 on 2018-03-19 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(default='null', max_length=6, verbose_name='Course Code')),
                ('courseName', models.CharField(default='null', max_length=50, verbose_name='Course Name')),
                ('courseCredit', models.PositiveSmallIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Course Credit')),
                ('department', models.CharField(default='null', max_length=4, verbose_name='Department')),
                ('definition', models.CharField(default='null', max_length=500, verbose_name='Definition')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=15, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('tcNumber', models.CharField(max_length=11, verbose_name='TC Number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('kadın', 'KADIN'), ('erkek', 'ERKEK')], default='Kadın', max_length=5, verbose_name='Sex')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Address')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(max_length=20, verbose_name='Current city')),
                ('phoneNumber', models.CharField(default='00000000000', max_length=11, verbose_name='Phone Number')),
                ('degree', models.CharField(choices=[('Lisans', 'LISANS'), ('Yuksek Lisans', 'YUKSEK LISANS'), ('Doktora', 'DOKTORA')], default='Lisans', max_length=20, verbose_name='Degree')),
                ('university', models.CharField(choices=[('FMV Isik University', 'FMV ISIK UNIVERSITY'), ('Galatasaray University', 'GALATASARAY UNIVERSITY')], default='Galatasaray University', max_length=50, verbose_name='University')),
                ('gpa', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='General Point Average')),
                ('scienceExam', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='ALES Point')),
                ('foreignLanguageExam', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='YDS Point')),
                ('program', models.CharField(choices=[('cse', 'CSE'), ('se', 'SE')], default='cse', max_length=40, verbose_name='Program')),
            ],
        ),
        migrations.CreateModel(
            name='OpenCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(default='null', max_length=6, verbose_name='Course Code')),
                ('courseName', models.CharField(default='null', max_length=50, verbose_name='Course Name')),
                ('courseCredit', models.PositiveSmallIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Course Credit')),
                ('department', models.CharField(default='null', max_length=4, verbose_name='Department')),
                ('courseClass', models.CharField(default='null', max_length=10, verbose_name='Course Class')),
                ('courseDescription', models.CharField(default='null', max_length=500, verbose_name='Course Description')),
                ('courseInstructor', models.CharField(blank=True, default='null', max_length=50, verbose_name='Course Instructor')),
                ('year', models.PositiveSmallIntegerField(default='2018', verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=15, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('tcNumber', models.CharField(max_length=11, verbose_name='TC Number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('kadın', 'KADIN'), ('erkek', 'ERKEK')], default='kadın', max_length=5, verbose_name='Sex')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Address')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(default='Istanbul', max_length=20, verbose_name='Current city')),
                ('phoneNumber', models.CharField(default='00000000000', max_length=11, verbose_name='Phone Number')),
                ('degree', models.CharField(choices=[('Lisans', 'LISANS'), ('Yuksek Lisans', 'YUKSEK LISANS'), ('Doktora', 'DOKTORA')], default='Lisans', max_length=20, verbose_name='Degree')),
                ('university', models.CharField(choices=[('FMV Isik University', 'FMV ISIK UNIVERSITY'), ('Galatasaray University', 'GALATASARAY UNIVERSITY')], default='Galatasaray University', max_length=50, verbose_name='University')),
                ('gpa', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='General Point Average')),
                ('scienceExam', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='ALES Point')),
                ('foreignLanguageExam', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='YDS Point')),
                ('program', models.CharField(choices=[('cse', 'CSE'), ('se', 'SE')], default='cse', max_length=40, verbose_name='Program')),
                ('academicSupervisior', models.CharField(max_length=50, verbose_name='Academic Supervisior')),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Statue')),
                ('scholarship', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Scholarship')),
                ('studentID', models.CharField(max_length=9, verbose_name='Student ID')),
                ('startingDate', models.DateField(default='2018-03-23', verbose_name='Starting Date')),
                ('endingDate', models.DateField(default='2018-03-23', verbose_name='Ending Date')),
                ('gpaI', models.PositiveSmallIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='GPA')),
                ('completedCredit', models.CharField(default='0', max_length=3, verbose_name='Completed Credit')),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectures', models.FileField(max_length=10, upload_to='', verbose_name='File field')),
            ],
        ),
    ]
