# Generated by Django 2.0.3 on 2018-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrandStudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='phoneNumber',
            field=models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='tcNumber',
            field=models.CharField(max_length=11, unique=True, verbose_name='TC Number'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='phoneNumber',
            field=models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='tcNumber',
            field=models.CharField(max_length=11, unique=True, verbose_name='TC Number'),
        ),
    ]
