# Generated by Django 2.0.4 on 2018-04-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0002_institute_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='birthday',
            new_name='establishedDate',
        ),
    ]
