# Generated by Django 2.0.4 on 2018-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0003_auto_20180414_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='establishedDate',
            field=models.DateField(null=True, verbose_name='established date'),
        ),
    ]
