GENDER = [('F', 'Female'),
          ('M', 'Male')]

'''This list is to choose city.'''
CITIES = [('1', 'Adana'),
          ('2', 'Adıyaman'),
          ('3', 'Afyonkarahisar'),
          ('4', 'Ağrı'),
          ('5', 'Amasya'),
          ('6', 'Ankara'),
          ('7', 'Antalya'),
          ('8', 'Artvin'),
          ('9', 'Aydın'),
          ('10', 'Balıkesir'),
          ('11', 'Bilecik'),
          ('12', 'Bingöl'),
          ('13', 'Bingöl'),
          ('14', 'Bolu'),
          ('15', 'Burdur'),
          ('16', 'Bursa'),
          ('17', 'Çanakkale'),
          ('18', 'Çankırı'),
          ('19', 'Çorum'),
          ('20', 'Denizli'),
          ('21', 'Diyarbakır'),
          ('22', 'Edirne'),
          ('23', 'Elazığ'),
          ('24', 'Erzincan'),
          ('25', 'Erzurum'),
          ('26', 'Eskişehir'),
          ('27', 'Gaziantep'),
          ('28', 'Giresun'),
          ('29', 'Gümüşhane'),
          ('30', 'Hakkâri'),
          ('31', 'Hatay'),
          ('32', 'Isparta'),
          ('33', 'Mersin'),
          ('34', 'İstanbul'),
          ('35', 'İzmir'),
          ('36', 'Kars'),
          ('37', 'Kastamonu'),
          ('38', 'Kayseri'),
          ('39', 'Kırklareli'),
          ('40', 'Kırşehir'),
          ('41', 'Kocaeli'),
          ('42', 'Konya'),
          ('43', 'Kütahya'),
          ('44', 'Malatya'),
          ('45', 'Manisa'),
          ('46', 'Kahramanmaraş'),
          ('47', 'Mardin'),
          ('48', 'Muğla'),
          ('49', 'Muş'),
          ('50', 'Nevşehir'),
          ('51', 'Niğde'),
          ('52', 'Ordu'),
          ('53', 'Rize'),
          ('54', 'Sakarya'),
          ('55', 'Samsun'),
          ('56', 'Siirt'),
          ('57', 'Sinop'),
          ('58', 'Sivas'),
          ('59', 'Tekirdağ'),
          ('60', 'Tokat'),
          ('61', 'Trabzon'),
          ('62', 'Tunceli'),
          ('63', 'Şanlıurfa'),
          ('64', 'Uşak'),
          ('65', 'Van'),
          ('66', 'Yozgat'),
          ('67', 'Zonguldak'),
          ('68', 'Aksaray'),
          ('69', 'Bayburt'),
          ('70', 'Karaman'),
          ('71', 'Kırıkkale'),
          ('72', 'Batman'),
          ('73', 'Şırnak'),
          ('74', 'Bartın'),
          ('75', 'Ardahan'),
          ('76', 'Iğdır'),
          ('77', 'Yalova'),
          ('78', 'Karabük'),
          ('79', 'Kilis'),
          ('80', 'Osmaniye'),
          ('81', 'Düzce')]

'''This is list to chooce degre.'''
DEGREES = [('1', 'Bachelor'),
           ('2', 'Master'),
           ('3', 'Doctorate')]

'''This list is to choose university.'''
UNIVERSITIES = [
    ('1', 'Işık Üniversitesi'),
    ('2', 'Abant İzzet Baysal Üniversitesi'),
    ('3', 'Adana Bilim ve Teknoloji Üniversitesi'),
    ('4', 'Adıyaman Üniversitesi'),
    ('5', 'Adnan Menderes Üniversitesi'),
    ('6', 'Afyon Kocatepe Üniversitesi'),
    ('7', 'Ağrı İbrahim Çeçen Üniversitesi'),
    ('8', 'Ahi Evran Üniversitesi'),
    ('9', 'Akdeniz Üniversitesi'),
    ('10', 'Aksaray Üniversitesi'),
    ('11', 'Alanya Alaaddin Keykubat Üniversitesi'),
    ('12', 'Amasya Üniversitesi'),
    ('13', 'Anadolu Üniversitesi'),
    ('14', 'Ankara Üniversitesi'),
    ('15', 'Ankara Sosyal Bilimler Üniversitesi'),
    ('16', 'Ardahan Üniversitesi'),
    ('17', 'Artvin Çoruh Üniversitesi'),
    ('18', 'Atatürk Üniversitesi'),
    ('19', 'Balıkesir Üniversitesi'),
    ('20', 'Bandırma Onyedi Eylül Üniversitesi'),
    ('21', 'Bartın Üniversitesi'),
    ('22', 'Batman Üniversitesi'),
    ('23', 'Bayburt Üniversitesi'),
    ('24', 'Bilecik Şeyh Edebali Üniversitesi'),
    ('25', 'Bingöl Üniversitesi'),
    ('26', 'Bitlis Eren Üniversitesi'),
    ('27', 'Boğaziçi Üniversitesi'),
    ('28', 'Bozok Üniversitesi'),
    ('29', 'Bursa Teknik Üniversitesi'),
    ('30', 'Celal Bayar Üniversitesi'),
    ('31', 'Cumhuriyet Üniversitesi'),
    ('32', 'Çanakkale Onsekiz Mart Üniversitesi'),
    ('33', 'Çankırı Karatekin Üniversitesi'),
    ('34', 'Çukurova Üniversitesi'),
    ('35', 'Deniz Harp Okulu'),
    ('36', 'Dicle Üniversitesi'),
    ('37', 'Dokuz Eylül Üniversitesi'),
    ('38', 'Dumlupınar Üniversitesi'),
    ('39', 'Düzce Üniversitesi'),
    ('40', 'Ege Üniversitesi'),
    ('41', 'Erciyes Üniversitesi'),
    ('42', 'Erzincan Üniversitesi'),
    ('43', 'Erzurum Teknik Üniversitesi'),
    ('44', 'Eskişehir Osmangazi Üniversitesi'),
    ('45', 'Fırat Üniversitesi'),
    ('46', 'Galatasaray Üniversitesi'),
    ('47', 'Gazi Üniversitesi'),
    ('48', 'Gaziantep Üniversitesi'),
    ('49', 'Gaziosmanpaşa Üniversitesi'),
    ('50', 'Gebze Teknik Üniversitesi'),
    ('51', 'Giresun Üniversitesi'),
    ('52', 'Gümüşhane Üniversitesi'),
    ('53', 'Hacettepe Üniversitesi'),
    ('54', 'Hakkari Üniversitesi'),
    ('55', 'Harran Üniversitesi'),
    ('56', 'Hava Harp Okulu'),
    ('57', 'Hitit Üniversitesi'),
    ('58', 'Iğdır Üniversitesi'),
    ('59', 'İnönü Üniversitesi'),
    ('60', 'İskenderun Teknik Üniversitesi'),
    ('61', 'İstanbul Medeniyet Üniversitesi'),
    ('62', 'İstanbul Üniversitesi'),
    ('63', 'İstanbul Teknik Üniversitesi'),
    ('64', 'İzmir Bakırçay Üniversitesi'),
    ('65', 'İzmir Demokrasi Üniversitesi'),
    ('66', 'İzmir Kâtip Çelebi Üniversitesi'),
    ('67', 'İzmir Yüksek Teknoloji Enstitüsü'),
    ('68', 'Kafkas Üniversitesi'),
    ('69', 'Kahramanmaraş Sütçü İmam Üniversitesi'),
    ('70', 'Karabük Üniversitesi'),
    ('71', 'Karadeniz Teknik Üniversitesi'),
    ('72', 'Karamanoğlu Mehmetbey Üniversitesi'),
    ('73', 'Kastamonu Üniversitesi'),
    ('74', 'Kırıkkale Üniversitesi'),
    ('75', 'Kilis 7 Aralık Üniversitesi'),
    ('76', 'Kocaeli Üniversitesi'),
    ('78', 'Necmettin Erbakan Üniversitesi'),
    ('79', 'Mardin Artuklu Üniversitesi'),
    ('80', 'Marmara Üniversitesi'),
    ('81', 'Mehmet Akif Ersoy Üniversitesi'),
    ('82', 'Mersin Üniversitesi'),
    ('83', 'Mimar Sinan Güzel Sanatlar Üniversitesi'),
    ('84', 'Muğla Sıtkı Koçman Üniversitesi'),
    ('85', 'Mustafa Kemal Üniversitesi'),
    ('86', 'Muş Alparslan Üniversitesi'),
    ('87', 'Namık Kemal Üniversitesi'),
    ('88', 'Nevşehir Hacı Bektaş Veli Üniversitesi'),
    ('89', 'Niğde Üniversitesi'),
    ('90', 'Ondokuz Mayıs Üniversitesi'),
    ('91', 'Ordu Üniversitesi'),
    ('92', 'Orta Doğu Teknik Üniversitesi'),
    ('93', 'Osmaniye Korkut Ata Üniversitesi'),
    ('94', 'Pamukkale Üniversitesi'),
    ('95', 'Sakarya Üniversitesi'),
    ('96', 'Selçuk Üniversitesi'),
    ('97', 'Siirt Üniversitesi'),
    ('98', 'Süleyman Demirel Üniversitesi'),
    ('99', 'Trakya Üniversitesi'),
    ('100', 'Uludağ Üniversitesi'),
    ('101', 'Uşak Üniversitesi'),
    ('102', 'Yalova Üniversitesi'),
    ('103', 'Yıldız Teknik Üniversitesi'),
    ('104', 'Yıldırım Beyazıt Üniversitesi'),
    ('105', 'Yüzüncü Yıl Üniversitesi'),
    ('106', 'Bülent Ecevit Üniversitesi'),
    ('107', 'Acıbadem Üniversitesi'),
    ('108', 'Akev Üniversitesi'),
    ('109', 'Anka Teknoloji Üniversitesi'),
    ('110', 'Atılım Üniversitesi'),
    ('111', 'Avrasya Üniversitesi'),
    ('112', 'Bahçeşehir Üniversitesi'),
    ('113', 'Başkent Üniversitesi'),
    ('114', 'Beykent Üniversitesi'),
    ('115', 'Bezmiâlem Vakıf Üniversitesi'),
    ('116', 'Bilkent Üniversitesi'),
    ('117', 'Biruni Üniversitesi'),
    ('118', 'Çankaya Üniversitesi'),
    ('119', 'Çağ Üniversitesi'),
    ('120', 'Doğuş Üniversitesi'),
    ('121', 'Fatih Sultan Mehmet Üniversitesi'),
    ('122', 'Haliç Üniversitesi'),
    ('123', 'İstanbul 29 Mayıs Üniversitesi'),
    ('124', 'İstanbul Arel Üniversitesi'),
    ('125', 'İstanbul Aydın Üniversitesi'),
    ('126', 'İstanbul Bilgi Üniversitesi'),
    ('127', 'İstanbul Gelişim Üniversitesi'),
    ('128', 'İstanbul Kemerburgaz Üniversitesi'),
    ('129', 'İstanbul Kültür Üniversitesi'),
    ('130', 'İstanbul Medipol Üniversitesi'),
    ('131', 'İstanbul Şehir Üniversitesi'),
    ('132', 'İstinye Üniversitesi'),
    ('132', 'İzmir Ekonomi Üniversitesi'),
    ('133', 'Kadir Has Üniversitesi'),
    ('134', 'Nişantaşı Üniversitesi'),
    ('135', 'Okan Üniversitesi'),
    ('136', 'Özyeğin Üniversitesi'),
    ('137', 'Piri Reis Üniversitesi'),
    ('138', 'Sabancı Üniversitesi'),
    ('139', 'TED Üniversitesi'),
    ('140', 'Yeditepe Üniversitesi')]

PROGRAM_TYPES = [('Master', 'The Master of Science Program'),
                 ('Doctoral', 'The Doctor of Philosophy Program')]

SEMESTERS = [('Summer', 'Summer'),
             ('Fall', 'Fall'),
             ('Spring', 'Spring')]

SLOTS = (('1', '9-10'),
         ('2', '10-11'),
         ('3', '11-12'),
         ('4', '12-13'),
         ('5', '13-14'),
         ('6', '14-15'),
         ('7', '15-16'),
         ('8', '16-17'),
         ('9', '17-18'),
         ('10', '18-19'),
         ('11', '19-20'),
         ('12', '20-21'),
         ('13', '21-22'))

DAYS = (('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
        ('6', 'Saturday'),
        ('7', 'Sunday'))

PLACES = (('1', 'DMF-101'),
          ('2', 'DMF-102'),
          ('3', 'DMF-103'))

GRADES = (('AA', 'AA'),
          ('BA', 'BA'),
          ('BB', 'BB'),
          ('CB', 'CB'),
          ('CC', 'CC'),
          ('DC', 'DC'),
          ('DD', 'DD'),
          ('F', 'F'),
          ('W', 'W'))

YEAR_IN_SCHOOL_CHOICES = (
    ('FR', 'Freshman'),
    ('SO', 'Sophomore'),
    ('JR', 'Junior'),
    ('SR', 'Senior'),
    ('GR', 'Graduate'),
)

BLOOD_TYPES = (('A Rh+', 'A Rh+'),
               ('B Rh+', 'B Rh+'),
               ('AB Rh+', 'AB Rh+'),
               ('0 Rh+', '0 Rh+'),
               ('A Rh-', 'A Rh-'),
               ('B Rh-', 'B Rh-'),
               ('AB Rh-', 'AB Rh-'),
               ('0 Rh-', '0 Rh-'))

MARITAL_STATUS = (('Single', 'Single'),
                  ('Married', 'Married'))


#### YENi EKLENENLER ####
EXAMSLOTS = (('1', '1'),
        ('2', '2'),
        ('3', '3'))

