# Generated by Django 2.0.3 on 2018-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=15, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=15, verbose_name='Last Name')),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('tcNumber', models.CharField(max_length=11, unique=True, verbose_name='TC Number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('erkek', 'ERKEK'), ('kadın', 'KADIN')], default='kadın', max_length=5, verbose_name='Sex')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Address')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(default='null', max_length=20, verbose_name='Current city')),
                ('phoneNumber', models.CharField(default='null', max_length=11, unique=True, verbose_name='Phone Number')),
                ('ssn', models.CharField(default='null', max_length=11, verbose_name='SSN')),
            ],
        ),
    ]
