# Generated by Django 2.0.3 on 2018-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstituteStaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='startingDate',
            field=models.DateTimeField(default='2018-03-23', verbose_name='Starting Date'),
        ),
    ]
