# Generated by Django 2.0.3 on 2018-03-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstituteStaff', '0002_personalinformation_startingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='startingDate',
        ),
    ]
