# Generated by Django 2.0.3 on 2018-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstituteStaff', '0003_remove_personalinformation_startingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='null', max_length=500, verbose_name='Text')),
            ],
        ),
    ]
