# Generated by Django 2.0.4 on 2018-04-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_head',
            new_name='head',
        ),
    ]
