# Generated by Django 2.0.4 on 2018-04-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='program',
            field=models.ForeignKey(default='IN PROGRESS', null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Program'),
        ),
    ]
