# Generated by Django 2.0.4 on 2018-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_auto_20180417_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='establishedDate',
            field=models.DateField(auto_now_add=True, default='2017-03-11', verbose_name='established date'),
            preserve_default=False,
        ),
    ]
