# Generated by Django 2.0.4 on 2018-06-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_adamekle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=6, null=True, verbose_name='Place')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.Section')),
            ],
        ),
    ]
