# Generated by Django 2.0.4 on 2018-04-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_auto_20180424_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='act_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.Section'),
        ),
    ]
