# Generated by Django 2.0.4 on 2018-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0003_auto_20180417_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='establishedDate',
            field=models.DateField(auto_now=True, verbose_name='established date'),
        ),
    ]
