# Generated by Django 2.0.4 on 2018-05-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0003_auto_20180425_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='special_quota',
            field=models.ManyToManyField(blank=True, null=True, related_name='special_quota', to='Institute.Student'),
        ),
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='Institute.Student'),
        ),
    ]
