# Generated by Django 2.0.4 on 2018-04-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0004_auto_20180417_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='establishedDate',
            field=models.DateField(verbose_name='established date'),
        ),
    ]
