# Generated by Django 2.0.4 on 2018-04-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0005_auto_20180417_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoataManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute.AcademicStaff')),
            ],
            options={
                'ordering': ['quota_manager'],
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='quota_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute.QuoataManager'),
        ),
    ]
