# Generated by Django 2.0.4 on 2018-04-21 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0006_auto_20180417_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute.AcademicStaff')),
            ],
        ),
        migrations.RemoveField(
            model_name='quoatamanager',
            name='quota_manager',
        ),
        migrations.AddField(
            model_name='section',
            name='quota',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Quota Quanitity'),
        ),
        migrations.AlterField(
            model_name='program',
            name='quota_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute.QuotaManager'),
        ),
        migrations.DeleteModel(
            name='QuoataManager',
        ),
    ]
