# Generated by Django 2.0.4 on 2018-06-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0006_auto_20180603_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examdates',
            options={'verbose_name': 'Exam Date', 'verbose_name_plural': 'Exam Dates'},
        ),
    ]
