# Generated by Django 2.0.4 on 2018-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0007_auto_20180603_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdates',
            name='slot',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, null=True, verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='examdates',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='Section Slot'),
        ),
    ]
